#!/bin/bash

# smartfile/publish
# =================
#
# Publishes a file on smartfile using the default build path.
# This is:
# * unstable builds (branches): dev/[repo]/unstable/[branch]/[build_id]-[git_tag]
# * stable build (tags): dev/[repo]/stable/[tag]
#
# Usage
# -----
# publish <auth-token> <file>
#
# Environment
# -----------
# SMARTFILE_AUTH: Smartfile credentials

set -e

if [[ $TRAVIS_PULL_REQUEST != "false" ]]
then
	echo "Skipping publish in pull request build."
	exit 0;
fi

if [[ ! -f $1 ]]
then
	echo "No valid file: '$1'."
	exit 1
fi

TAG=`git describe --tags --always --match version/*`
VERSION=${TAG#version/}
	
# Default upload dir, if on a branch.
UPLOAD_DIR="dev/$TRAVIS_REPO_SLUG/unstable/${TRAVIS_BRANCH}/${TRAVIS_BUILD_NUMBER}-${VERSION}"

# If we are building a release, the repo slug is the tag name.
# The tag name is yielded by git describe, iff the current commit is a tag.
if [[ $TAG == $TRAVIS_BRANCH ]]
then
	UPLOAD_DIR="dev/$TRAVIS_REPO_SLUG/stable/${VERSION}"
fi

$(dirname $BASH_SOURCE)/upload $1 $UPLOAD_DIR
