#!/bin/bash

# smartfile/upload
# ================
#
# Uploads a file to a specific directory on smartfile. 
# The directory will be created automatically.
#
# Usage
# -----
# publish <file> <path>
#
# Environment
# -----------
# SMARTFILE_AUTH: Smartfile credentials

set -e

if [[ ! -n $SMARTFILE_AUTH ]]
then
	echo "No auth token provided."
	exit 1
fi

if [[ ! -f $1 ]]
then
	echo "No valid file: '$1'."
	exit 1
fi


if [[ ! -f $2 ]]
then
	echo "No valid path: '$2'."
	exit 1
fi

echo "Uploading '$1' to '$2'"

# ensure dir exists
curl -sS -u $SMARTFILE_AUTH -X PUT "https://app.smartfile.com/api/2/path/oper/mkdir/$UPLOAD_DIR" 1>/dev/null

#upload file
curl -sS -u $SMARTFILE_AUTH -F file=@"$1" "https://app.smartfile.com/api/2/path/oper/mkdir/$UPLOAD_DIR" 1>/dev/null
